[project]
name = "most"
version = "0.1.0"
description = "A text file viewer"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
most = "most.cli:main"

[tool.setuptools]
ext-modules = [
    {name = "most.cmost", sources = ["src/cmost.c"], extra-compile-args = ["-Werror", "-Wall"]}
]
